### PR TITLE
Fix empty slice

### LINKED ISSUE #1195: Calling Slice() on an empty object crashes
```
TEST(Manifold, SliceEmptyObject) {
  Manifold cube;
  CrossSection bottom = cube.Slice();
}
```

Stack trace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001011af9f0 libmanifold.3.dylib`manifold::collider_internal::FindCollision<manifold::Box, false, manifold::SimpleRecorder<manifold::Manifold::Impl::Slice(double) const::$_0>>::operator()(this=0x000000016fdfe558, queryIdx=0) at collider.h:190:48
    frame #1: 0x00000001011af958 libmanifold.3.dylib`manifold::collider_internal::FindCollision<manifold::Box, false, manifold::SimpleRecorder<manifold::Manifold::Impl::Slice(double) const::$_0>> std::__1::for_each[abi:ne180100]<manifold::CountingIterator<unsigned long>, manifold::collider_internal::FindCollision<manifold::Box, false, manifold::SimpleRecorder<manifold::Manifold::Impl::Slice(double) const::$_0>>>(__first=(counter = 0), __last=(counter = 1), __f=FindCollision<manifold::Box, false, manifold::SimpleRecorder<(lambda at /Users/kintel/code/OpenSCAD/checkout/manifold/src/face_op.cpp:384:26)> > @ 0x000000016fdfe558) at for_each.h:34:5
    frame #2: 0x00000001011af8b4 libmanifold.3.dylib`void manifold::for_each<manifold::CountingIterator<unsigned long>, manifold::collider_internal::FindCollision<manifold::Box, false, manifold::SimpleRecorder<manifold::Manifold::Impl::Slice(double) const::$_0>>>(policy=Seq, first=(counter = 0), last=(counter = 1), f=FindCollision<manifold::Box, false, manifold::SimpleRecorder<(lambda at /Users/kintel/code/OpenSCAD/checkout/manifold/src/face_op.cpp:384:26)> > @ 0x000000016fdfe5e8) at parallel.h:392:3
    frame #3: 0x00000001011af850 libmanifold.3.dylib`void manifold::for_each_n<manifold::CountingIterator<unsigned long>, manifold::collider_internal::FindCollision<manifold::Box, false, manifold::SimpleRecorder<manifold::Manifold::Impl::Slice(double) const::$_0>>>(policy=Seq, first=(counter = 0), n=1, f=FindCollision<manifold::Box, false, manifold::SimpleRecorder<(lambda at /Users/kintel/code/OpenSCAD/checkout/manifold/src/face_op.cpp:384:26)> > @ 0x000000016fdfe690) at parallel.h:402:3
    frame #4: 0x00000001011a10a0 libmanifold.3.dylib`void manifold::Collider::Collisions<false, manifold::Box, manifold::SimpleRecorder<manifold::Manifold::Impl::Slice(double) const::$_0>>(this=0x00000001210043e0, queriesIn=0x000000016fdfe8f0, recorder=0x000000016fdfe900, parallel=false) const at collider.h:326:5
    frame #5: 0x00000001011a09f4 libmanifold.3.dylib`manifold::Manifold::Impl::Slice(this=0x00000001210042b8, height=0) const at face_op.cpp:399:13
    frame #6: 0x00000001011d1638 libmanifold.3.dylib`manifold::Manifold::Slice(this=0x000000016fdfeac8, height=0) const at manifold.cpp:978:38
```

### PR DESCRIPTION
**Pull request by pca006132**
Closes #1195

### CODE REVIEW

File: test/manifold_test.cpp [hunk 1]
```diff
@@ -495,6 +495,11 @@ TEST(Manifold, Slice) {
   EXPECT_EQ(bottom.Area(), 1);
   EXPECT_EQ(top.Area(), 0);
 }
+
+TEST(Manifold, SliceEmptyObject) {
+  Manifold cube;
+  CrossSection bottom = cube.Slice();
```
Comment (elalish) [inline test/manifold_test.cpp:501]: Maybe `empty` instead of `cube`? Might also be good to check that `bottom` is empty.

**Review by elalish — APPROVED** [review]
Thanks!
