### PR TITLE
Fix NaN halfedgeTangents

### LINKED ISSUE #584: vec out of range with sdf, smooth and refine
```cpp
TEST(SDF, SineSurface) {
  Mesh surface(LevelSet(
      [](glm::vec3 p) {
        float mid = glm::sin(p.x) + glm::sin(p.y);
        return (p.z > mid - 0.5 && p.z < mid + 0.5) ? 1 : 0;
      },
      {glm::vec3(-4 * glm::pi<float>()), glm::vec3(4 * glm::pi<float>())}, 1));
  Manifold smoothed = Manifold::Smooth(surface).Refine(2);
#ifdef MANIFOLD_EXPORT
  if (options.exportModels)
    ExportMesh("sinesurface.stl", smoothed.GetMesh(), {});
#endif
}
```

Error:
```
0x000055555575da20 in (anonymous namespace)::FaceMortonBox::operator() (this=this@entry=0x7fffeb04ac78, inout=...) at _deps/thrust-src/thrust/detail/function.h:126
```

and it seems that it is quite specific to this SDF function.

### PR DESCRIPTION
**Pull request by elalish**
Fixes #584

### CODE REVIEW

File: test/sdf_test.cpp [hunk 1]
```diff
@@ -115,3 +115,21 @@ TEST(SDF, Resize) {
...
+  Mesh surface(LevelSet(
+      [](glm::vec3 p) {
+        float mid = glm::sin(p.x) + glm::sin(p.y);
+        return (p.z > mid - 0.5 && p.z < mid + 0.5) ? 1 : 0;
+      },
+      {glm::vec3(-4 * glm::pi<float>()), glm::vec3(4 * glm::pi<float>())}, 1));
+  Manifold smoothed = Manifold::Smooth(surface).Refine(2);
+
+  EXPECT_EQ(smoothed.Status(), Manifold::Error::NoError);
+  EXPECT_EQ(smoothed.Genus(), -2);
```
Comment (elalish) [inline test/sdf_test.cpp:129]: @pca006132 I'm a little surprised this is -2 maybe some small disconnected object somewhere, or tiny hole? The model looks like it ought to be 0. I'm not too worried about it for now, but might be worth looking into at some point.
