### PR TITLE
fix degenerate hulls

### LINKED ISSUE #1491: Use-after-free in QuickHull::buildMesh when computing Hull of a 0-degree Revolve
Hi, there is a potential bug in `QuickHull::buildMesh` reachable with crafted manifolds.

This bug was reproduced on https://github.com/elalish/manifold/commit/213bcc5bd1652fe25d173bbbc39129cb1f32de8d.

### Description

What crashes
- Calling Manifold::Revolve() with a valid rectangular cross-section but revolveDegrees=0.0 creates a degenerate manifold. Invoking Manifold::Hull() on this object triggers a heap use-after-free read inside QuickHull::buildMesh.

Evidence from ASan/stacktrace
- The top frame is a memcpy from originalVertexData at quickhull.cpp:311: vertices[counts[i]] = originalVertexData[i].
- The same function previously called Vec<vec3>::clear(true) at quickhull.cpp:251, which frees the buffer via free_async() -> shrink_to_fit(). ASan shows the freed region and the later read from the same address.
- Call chain: Manifold::Hull() -> Impl::Hull() -> QuickHull::buildMesh() -> for_each(...) reading from originalVertexData after it was freed.

Trigger characterization and A/B check
- Reproducer with Revolve(..., degrees=0.0) followed by Hull() crashes reliably.
- A/B: Changing only revolveDegrees to 360.0 (keeping the same cross-section and circularSegments) eliminates the crash; Hull completes and returns a mesh. This shows the crash requires a crafted parameter (0-degree revolve) and is not a general instability.

### POC

The following testcase demonstrates the bug:

**testcase.cpp**
```cpp
#include "/fuzz/install/include/manifold/common.h"
#include "/fuzz/install/include/manifold/manifold.h"
int main(){
  // Simple rectangle cross-section
  manifold::SimplePolygon contour;
  contour.push_back({0.0,0.0});
  contour.push_back({0.5,0.0});
  contour.push_back({0.5,1.0});
  contour.push_back({0.0,1.0});
  manifold::Polygons cs; cs.push_back(contour);
  // Revolve by 0 degrees produces a degenerate/empty surface
  manifold::Manifold m = manifold::Manifold::Revolve(cs, /*circularSegments=*/32, /*revolveDegrees=*/0.0);
  // Taking the convex hull triggers a UAF inside QuickHull::buildMesh
  manifold::Manifold h = m.Hull();
  volatile size_t n = h.NumTri(); (void)n;
  return 0;
}

```

**stdout**
```text

```

**stderr**
```text
=================================================================
==1==ERROR: AddressSanitizer: heap-use-after-free on address 0x51f000003880 at pc 0x556d7881d9aa bp 0x7ffe317f51b0 sp 0x7ffe317f4970
READ of size 24 at 0x51f000003880 thread T0
    #0 0x556d7881d9a9 in __asan_memcpy (/fuzz/test+0xc99a9) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #1 0x556d78a61bc2 in manifold::QuickHull::buildMesh(double)::$_4::operator()(unsigned long) const quickhull.cpp
    #2 0x556d78a61900 in manifold::QuickHull::buildMesh(double)::$_4 std::for_each<manifold::CountingIterator<unsigned long>, manifold::QuickHull::buildMesh(double)::$_4>(manifold::CountingIterator<unsigned long>, manifold::CountingIterator<unsigned long>, manifold::QuickHull::buildMesh(double)::$_4) quickhull.cpp
    #3 0x556d78a5b4b5 in void manifold::for_each<manifold::CountingIterator<unsigned long>, manifold::QuickHull::buildMesh(double)::$_4>(manifold::ExecutionPolicy, manifold::CountingIterator<unsigned long>, manifold::CountingIterator<unsigned long>, manifold::QuickHull::buildMesh(double)::$_4) quickhull.cpp
    #4 0x556d78a55edb in manifold::QuickHull::buildMesh(double) (/fuzz/test+0x301edb) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #5 0x556d78a5ee2f in manifold::Manifold::Impl::Hull(manifold::VecView<linalg::vec<double, 3>>) (/fuzz/test+0x30ae2f) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #6 0x556d789bfe1e in manifold::Manifold::Hull() const (/fuzz/test+0x26be1e) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #7 0x556d7885ebff in main /fuzz/testcase.cpp:14:28
    #8 0x7ff847ecfd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #9 0x7ff847ecfe3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #10 0x556d78783544 in _start (/fuzz/test+0x2f544) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)

0x51f000003880 is located 0 bytes inside of 3264-byte region [0x51f000003880,0x51f000004540)
freed by thread T0 here:
    #0 0x556d7881f646 in free (/fuzz/test+0xcb646) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #1 0x556d7889eff0 in manifold::Vec<linalg::vec<double, 3>, false>::free_async(linalg::vec<double, 3>*, unsigned long) (/fuzz/test+0x14aff0) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #2 0x556d7889ef01 in manifold::Vec<linalg::vec<double, 3>, false>::shrink_to_fit() (/fuzz/test+0x14af01) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #3 0x556d78982494 in manifold::Vec<linalg::vec<double, 3>, false>::clear(bool) (/fuzz/test+0x22e494) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #4 0x556d78a55124 in manifold::QuickHull::buildMesh(double) (/fuzz/test+0x301124) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #5 0x556d78a5ee2f in manifold::Manifold::Impl::Hull(manifold::VecView<linalg::vec<double, 3>>) (/fuzz/test+0x30ae2f) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #6 0x556d789bfe1e in manifold::Manifold::Hull() const (/fuzz/test+0x26be1e) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #7 0x556d7885ebff in main /fuzz/testcase.cpp:14:28
    #8 0x7ff847ecfd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x556d7881f8ee in malloc (/fuzz/test+0xcb8ee) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #1 0x556d7889eb58 in manifold::Vec<linalg::vec<double, 3>, false>::reserve(unsigned long) (/fuzz/test+0x14ab58) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #2 0x556d78872d9c in manifold::Vec<linalg::vec<double, 3>, false>::push_back(linalg::vec<double, 3> const&) (/fuzz/test+0x11ed9c) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #3 0x556d78a5d7be in manifold::QuickHull::setupInitialTetrahedron() (/fuzz/test+0x3097be) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #4 0x556d78a57522 in manifold::QuickHull::createConvexHalfedgeMesh() (/fuzz/test+0x303522) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #5 0x556d78a54f51 in manifold::QuickHull::buildMesh(double) (/fuzz/test+0x300f51) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #6 0x556d78a5ee2f in manifold::Manifold::Impl::Hull(manifold::VecView<linalg::vec<double, 3>>) (/fuzz/test+0x30ae2f) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #7 0x556d789bfe1e in manifold::Manifold::Hull() const (/fuzz/test+0x26be1e) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437)
    #8 0x556d7885ebff in main /fuzz/testcase.cpp:14:28
    #9 0x7ff847ecfd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-use-after-free (/fuzz/test+0xc99a9) (BuildId: aa2bde9495eb6565c5560a52fc00e5e36f877437) in __asan_memcpy
Shadow bytes around the buggy address:
  0x51f000003600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51f000003680: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x51f000003700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51f000003780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51f000003800: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x51f000003880:[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51f000003900: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51f000003980: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51f000003a00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51f000003a80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51f000003b00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1==ABORTING

```

<details><summary>Steps to Reproduce</summary>
<p>

The crash was triaged with the following Dockerfile:

**Dockerfile**
```dockerfile
# Ubuntu 22.04 with some packages pre-installed
FROM hgarrereyn/stitch_repro_base@sha256:3ae94cdb7bf2660f4941dc523fe48cd2555049f6fb7d17577f5efd32a40fdd2c

RUN git clone https://github.com/elalish/manifold /fuzz/src && \
    cd /fuzz/src && \
    git checkout 213bcc5bd1652fe25d173bbbc39129cb1f32de8d && \
    git submodule update --init --remote --recursive

ENV LD_LIBRARY_PATH=/fuzz/install/lib
ENV ASAN_OPTIONS=hard_rss_limit_mb=1024:detect_leaks=0

RUN echo '#!/bin/bash\nexec clang-17 -fsanitize=address -O0 "$@"' > /usr/local/bin/clang_wrapper && \
    chmod +x /usr/local/bin/clang_wrapper && \
    echo '#!/bin/bash\nexec clang++-17 -fsanitize=address -O0 "$@"' > /usr/local/bin/clang_wrapper++ && \
    chmod +x /usr/local/bin/clang_wrapper++

# Install required build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    ninja-build \
 && rm -rf /var/lib/apt/lists/*

# Configure, build, and install static library
RUN cmake -S /fuzz/src -B /tmp/build -G Ninja \
    -DCMAKE_C_COMPILER=clang_wrapper \
    -DCMAKE_CXX_COMPILER=clang_wrapper++ \
    -DCMAKE_INSTALL_PREFIX=/fuzz/install \
    -DBUILD_SHARED_LIBS=OFF \
    -DMANIFOLD_TEST=OFF \
    -DMANIFOLD_PYBIND=OFF \
    -DMANIFOLD_CBIND=OFF \
    -DMANIFOLD_JSBIND=OFF \
    -DMANIFOLD_EXPORT=OFF \
    -DMANIFOLD_PAR=OFF \
    -DMANIFOLD_CROSS_SECTION=OFF \
    -DMANIFOLD_DOWNLOADS=OFF \
 && cmake --build /tmp/build --target install -j$(nproc) \
 && rm -rf /tmp/build
```

**Build Command**
```bash
clang++-17 -fsanitize=address -g -O0 -o /fuzz/test /fuzz/testcase.cpp -I/fuzz/install/include -L/fuzz/install/lib -lmanifold && /fuzz/test
```

**Reproduce**
1. Copy `Dockerfile` and `testcase.cpp` into a local folder.
2. Build the repro image:
```bash
docker build . -t repro --platform=linux/amd64
```
3. Compile and run the testcase in the image:
```bash
docker run \
    -it --rm \
    --platform linux/amd64 \
    --mount type=bind,source="$(pwd)/testcase.cpp",target=/fuzz/testcase.cpp \
    repro \
    bash -c "clang++-17 -fsanitize=address -g -O0 -o /fuzz/test /fuzz/testcase.cpp -I/fuzz/install/include -L/fuzz/install/lib -lmanifold && /fuzz/test"
```

</p>
</details> 

---

### Additional Info
This testcase was discovered by `STITCH`, an autonomous fuzzing system. All reports are reviewed manually (by a human) before submission.

### PR DESCRIPTION
**Pull request by pca006132**
Fixes #1491. Just incorrect logic for handling degenerate cases. The issue found is for the 2D case, but I found that the 1D case can also be wrong so I also fixed it.

### CODE REVIEW

File: src/quickhull.cpp [hunk 1]
```diff
@@ -706,32 +702,16 @@ void QuickHull::setupInitialTetrahedron() {
   }
   if (maxD == epsilonSquared) {
     // It appears that the point cloud belongs to a 1 dimensional subspace of
-    // R^3: convex hull has no volume => return a thin triangle Pick any point
-    // other than selectedPoints.first and selectedPoints.second as the third
-    // point of the triangle
-    auto it =
```
Comment (pca006132) [inline src/quickhull.cpp:712]: The original code tried to find other points, but we are in a degenerate case anyway, so it doesn't really matter anyway...

**Comment by pca006132** [comment]
@elalish one question: should we treat hulls with less than 4 points as invalid construction, or should we return a proper degenerate mesh containing those points?

**Comment by elalish** [comment]
I think I'd return a two tri mesh. I believe if you make a two tri meshgl and pass it in and out of manifold, it will remain, so we should be consistent. I think it only vanishes when you call simplify.

**Comment by pca006132** [comment]
> I think I'd return a two tri mesh. I believe if you make a two tri meshgl and pass it in and out of manifold, it will remain, so we should be consistent. I think it only vanishes when you call simplify.

but I remember we will remove the opposing triangles. need to test that

**Comment by elalish** [comment]
>but I remember we will remove the opposing triangles. need to test that

Yeah, we used to, but I think we removed that to support zero-volume meshes for BRL CAD. I believe that logic is now only called when simplification happens, which is now mostly explicit instead of implicit.

**Comment by pca006132** [comment]
I see, will try that later.

**Review by elalish — APPROVED** [review]
That looks reasonable, thanks. Will the WASM thing get fixed if you pull master?

**Comment by elalish** [comment]
If you're returning a degenerate tet, that's fine too - I don't think it has to be a two-tri mesh.
