### PR TITLE
Fix test overflow

### LINKED ISSUE #101: heap-buffer-overflow for manifold_test
I've built the project with address sanitizer enabled:
```
cmake -DCMAKE_BUILD_TYPE=Release -DMANIFOLD_USE_CPP=on -DCMAKE_CUDA_COMPILER=$CUDACXX -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
```

and `Manifold.ManualSmooth` reports the following error:

```
==39777==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f2cc3a027dc at pc 0x0000021183e3 bp 0x7ffda836e930 sp 0x7ffda836e928
READ of size 4 at 0x7f2cc3a027dc thread T0
    #0 0x21183e2 in Manifold_ManualSmooth_Test::TestBody() /home/pca006132/code/manifold/test/mesh_test.cpp:308:36
    #1 0x21c3b10 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2443:10
    #2 0x21c3b10 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2479:14
    #3 0x218353f in testing::Test::Run() /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2517:5
    #4 0x2185399 in testing::TestInfo::Run() /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2693:11
    #5 0x2186cc6 in testing::TestCase::Run() /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2811:28
    #6 0x21a0607 in testing::internal::UnitTestImpl::RunAllTests() /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:5177:43
    #7 0x21c767f in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2443:10
    #8 0x21c767f in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:2479:14
    #9 0x219ef3e in testing::UnitTest::Run() /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/src/gtest.cc:4786:10
    #10 0x20e4ef5 in RUN_ALL_TESTS() /home/pca006132/code/manifold/build/third_party/google_test/googletest-src/googletest/include/gtest/gtest.h:2341:46
    #11 0x20e4ef5 in main /home/pca006132/code/manifold/test/test_main.cpp:50:10
    #12 0x7f2cc910778f in __libc_start_main (/nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib/libc.so.6+0x2778f)
    #13 0x2004589 in _start /build/glibc-2.33/csu/../sysdeps/x86_64/start.S:120

0x7f2cc3a027dc is located 36 bytes to the left of 494496-byte region [0x7f2cc3a02800,0x7f2cc3a7b3a0)
allocated by thread T0 here:
    #0 0x20e20e7 in operator new(unsigned long) (/home/pca006132/code/manifold/build/test/manifold_test+0x20e20e7)
    #1 0x21e7609 in __gnu_cxx::new_allocator<glm::vec<3, float, (glm::qualifier)0> >::allocate(unsigned long, void const*) /nix/store/wly4zlhr614xi6mb97d4r040d69ikkfw-gcc-10.3.0/include/c++/10.3.0/ext/new_allocator.h:115:42
    #2 0x21e7609 in std::allocator_traits<std::allocator<glm::vec<3, float, (glm::qualifier)0> > >::allocate(std::allocator<glm::vec<3, float, (glm::qualifier)0> >&, unsigned long) /nix/store/wly4zlhr614xi6mb97d4r040d69ikkfw-gcc-10.3.0/include/c++/10.3.0/bits/alloc_traits.h:460:22
    #3 0x21e7609 in std::_Vector_base<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > >::_M_allocate(unsigned long) /nix/store/wly4zlhr614xi6mb97d4r040d69ikkfw-gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:346:36
    #4 0x21e7609 in void std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > >::_M_range_insert<thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*> >(__gnu_cxx::__normal_iterator<glm::vec<3, float, (glm::qualifier)0>*, std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > > >, thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>, thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>, std::forward_iterator_tag) /nix/store/wly4zlhr614xi6mb97d4r040d69ikkfw-gcc-10.3.0/include/c++/10.3.0/bits/vector.tcc:769:38
    #5 0x21e7609 in void std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > >::_M_insert_dispatch<thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*> >(__gnu_cxx::__normal_iterator<glm::vec<3, float, (glm::qualifier)0>*, std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > > >, thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>, thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>, std::__false_type) /nix/store/wly4zlhr614xi6mb97d4r040d69ikkfw-gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:1665:16
    #6 0x21e7609 in __gnu_cxx::__normal_iterator<glm::vec<3, float, (glm::qualifier)0>*, std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > > > std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > >::insert<thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>, void>(__gnu_cxx::__normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*, std::vector<glm::vec<3, float, (glm::qualifier)0>, std::allocator<glm::vec<3, float, (glm::qualifier)0> > > >, thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>, thrust::detail::normal_iterator<glm::vec<3, float, (glm::qualifier)0> const*>) /nix/store/wly4zlhr614xi6mb97d4r040d69ikkfw-gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:1383:19
    #7 0x21e7609 in manifold::Manifold::GetMeshRelation() const /home/pca006132/code/manifold/manifold/src/manifold.cu:277:111

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/pca006132/code/manifold/test/mesh_test.cpp:308:36 in Manifold_ManualSmooth_Test::TestBody()
Shadow bytes around the buggy address:
  0x0fe6187384a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe6187384b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe6187384c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe6187384d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe6187384e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0fe6187384f0: fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa fa
  0x0fe618738500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe618738510: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe618738520: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe618738530: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe618738540: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==39777==ABORTING
```

### PR DESCRIPTION
**Pull request by elalish**
Fixes #101 

A simple one-liner, but while I was at it, I cleaned up the tests a little, making them export via the command line like the samples. I also removed the imports for Csaszar, since it was simple enough to include. That only leaves the gyroidpuzzle being imported now.

### CODE REVIEW

File: test/mesh_test.cpp [hunk 1]
```diff
@@ -295,52 +322,56 @@ TEST(Manifold, ManualSmooth) {
...
+    options.faceted = false;
+    options.mat.roughness = 0.1;
+
+    options.mat.vertColor.resize(interp.NumVert());
+    MeshRelation rel = interp.GetMeshRelation();
+    const glm::vec4 red(1, 0, 0, 1);
+    const glm::vec4 purple(1, 0, 1, 1);
+    for (int tri = 0; tri < interp.NumTri(); ++tri) {
+      for (int i : {0, 1, 2}) {
+        const glm::vec3& uvw = rel.UVW(tri, i);
```
Comment (elalish) [inline test/mesh_test.cpp:337]: The was the actual bug fix; forgot to use my helper function.
