### PR TITLE
Fix face removal (#1191)

### LINKED ISSUE #1191: regression on meshgl with touching faces
It seems that this is due to simplification or something. I checked that reverting the previous 3 PRs (determinism and parallelization of CreateHalfedges) doesn't solve the problem, so it is probably something earlier.

```scad
// Two cubes sharing a face.
// This is a non-manifold object since the collapsed vertices are not distinct.
polyhedron(
  points=[
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [1, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 1],

    [2, 0, 0],
    [2, 1, 0],
    [2, 0, 1],
    [2, 1, 1],
  ],
  faces=[
    [6,7,5],[6,5,4],
    [0,1,3],[0,3,2],
    [4,5,1],[4,1,0],
    [5,7,3],[5,3,1],
    [7,6,2],[7,2,3],
    [4,0,2],[4,2,6],
    [7,11,10],[7,10,5],
    [1,8,9],[1,9,3],
    [5,10,8],[5,8,1],
    [10,11,9],[10,9,8],
    [11,7,3],[11,3,9],
    [5,1,3],[5,3,7],
  ]);
```

Expected:

Image

What we got:

Image

### PR DESCRIPTION
**Pull request by pca006132**
Closes #1191.

The bulk of the code is handling removed faces. Instead of letting them sit in the vector, I remove them and reorder properties dependent on this. This avoids the need to make other functions accept removed halfedges.

While writing this, something that comes to my mind is that we are not really trying our best to handle cases that are not 2-manifold. The current matching method may produce pairs that cross-cross together. I think one way to handle this is to sort the duplicated halfedges according to the face normals, so we will not produce any criss-crossing pairs. Probably for another issue, though.

### CODE REVIEW

**Review by elalish — COMMENTED** [review]
Thanks for digging into this!

File: src/impl.cpp [hunk 1]
```diff
@@ -348,23 +357,111 @@ void Manifold::Impl::CreateHalfedges(const Vec<ivec3>& triVerts) {
...
            });
 #else
-  for (int i = 0; i < numEdge; ++i) body(i, numEdge);
+  int consecutiveStart = 0;
+  for (int i = 0; i < numEdge; ++i)
+    consecutiveStart = body(i, consecutiveStart, numEdge);
 #endif
 
+  if (!removedHalfedges.empty()) {
+    // Remove the marked halfedges
```
[the remark this answers is not in the document]
Comment (pca006132) [reply src/impl.cpp]: Yeah make sense, I just added the checks elsewhere and keep the removed halfedges in-place.

**Comment by pca006132** [comment]
Weird, I can't reproduce the failure.

**Comment by pca006132** [comment]
OK some uninitialized memory stuff. Here we go again.

File: src/impl.cpp [hunk 2]
```diff
@@ -306,25 +311,30 @@ void Manifold::Impl::CreateHalfedges(const Vec<ivec3>& triVerts) {
...
     while (1) {
       const int pair1 = ids[k];
-      Halfedge h1 = halfedge_[pair1];
+      Halfedge& h1 = halfedge_[pair1];
       if (h0.startVert != h1.endVert || h0.endVert != h1.startVert) break;
       if (halfedge_[NextHalfedge(pair0)].endVert ==
           halfedge_[NextHalfedge(pair1)].endVert) {
-        h0 = {-1, -1, -1};
-        h1 = {-1, -1, -1};
+        h0.pairedHalfedge = h1.pairedHalfedge = -2;
```
Comment (elalish) [inline src/impl.cpp:325]: perhaps we should start using named constants?

File: test/sdf_test.cpp [hunk 3]
```diff
@@ -42,7 +42,7 @@ TEST(SDF, SphereShell) {
       },
       {vec3(-1.1), vec3(1.1)}, 0.01, 0, 0.0001);
 
-  EXPECT_NEAR(sphere.Genus(), 11500, 1000);
+  EXPECT_NEAR(sphere.Genus(), 14235, 1000);
```
Comment (elalish) [inline test/sdf_test.cpp:45]: Does this still look good, or look better? I recall working to remove little bits of infinitely thin geometry on this one.

**Review by elalish — APPROVED** [review]

File: test/sdf_test.cpp (hunk 3 above)
Comment (pca006132) [reply test/sdf_test.cpp:45]: I don't see infinitely thin stuff, but I see something that looks like self-intersection:

image

This is probably related to the other thing I mentioned, as there are many  non-2-manifold edges here.

Comment (elalish) [reply test/sdf_test.cpp:45]: Ah, right - I think my slick pre-edge collapse thing in the SDF can create even manifold edges. We should probably look at that again and see if there's a better way. I believe without that it's all guaranteed 2-manifold.
