### PR TITLE
please gcc

### LINKED ISSUE #460: Crash while building
While building on my computer I get the following error:

```
[ 22%] Building CXX object src/manifold/CMakeFiles/manifold.dir/src/boolean_result.cpp.o
cd /app/manifold/build/src/manifold && /usr/bin/c++ -Dmanifold_EXPORTS -I/app/manifold/src/manifold/include -I/app/manifold/src/utilities/include -I/app/manifold/src/third_party/thrust/dependencies/libcudacxx/include -I/app/manifold/src/third_party/thrust -I/app/manifold/src/third_party/glm/glm/.. -I/app/manifold/src/cross_section/include -I/app/manifold/src/third_party/clipper2/CPP/Clipper2Lib/include -I/app/manifold/src/collider/include -I/app/manifold/src/polygon/include -I/app/manifold/src/third_party/graphlite/include -O3 -DNDEBUG -fPIC -fPIC -Werror -Wall -Wno-sign-compare -Wno-unused -O3 -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP -std=gnu++17 -MD -MT src/manifold/CMakeFiles/manifold.dir/src/boolean_result.cpp.o -MF CMakeFiles/manifold.dir/src/boolean_result.cpp.o.d -o CMakeFiles/manifold.dir/src/boolean_result.cpp.o -c /app/manifold/src/manifold/src/boolean_result.cpp
In file included from /app/manifold/src/utilities/include/sparse.h:22,
                 from /app/manifold/src/collider/include/collider.h:17,
                 from /app/manifold/src/manifold/src/impl.h:18,
                 from /app/manifold/src/manifold/src/boolean3.h:16,
                 from /app/manifold/src/manifold/src/boolean_result.cpp:18:
In static member function ‘static void manifold::ManagedVec<T>::mallocManaged(T**, size_t) [with T = int]’,
    inlined from ‘std::tuple<manifold::VecDH<int>, manifold::VecDH<int> > {anonymous}::SizeOutput(manifold::Manifold::Impl&, const manifold::Manifold::Impl&, const manifold::Manifold::Impl&, const manifold::VecDH<int>&, const manifold::VecDH<int>&, const manifold::VecDH<int>&, const manifold::VecDH<int>&, const manifold::SparseIndices&, const manifold::SparseIndices&, bool, manifold::ExecutionPolicy)’ at /app/manifold/src/utilities/include/vec_dh.h:155:20:
/app/manifold/src/utilities/include/vec_dh.h:261:42: error: argument 1 value ‘18446744073709551612’ exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
       *ptr = reinterpret_cast<T *>(malloc(bytes));
                                    ~~~~~~^~~~~~~
In file included from /usr/include/c++/8/cstdlib:75,
                 from /usr/include/c++/8/bits/stl_algo.h:59,
                 from /usr/include/c++/8/algorithm:62,
                 from /app/manifold/src/manifold/src/boolean_result.cpp:15:
/usr/include/stdlib.h: In function ‘std::tuple<manifold::VecDH<int>, manifold::VecDH<int> > {anonymous}::SizeOutput(manifold::Manifold::Impl&, const manifold::Manifold::Impl&, const manifold::Manifold::Impl&, const manifold::VecDH<int>&, const manifold::VecDH<int>&, const manifold::VecDH<int>&, const manifold::VecDH<int>&, const manifold::SparseIndices&, const manifold::SparseIndices&, bool, manifold::ExecutionPolicy)’:
/usr/include/stdlib.h:539:14: note: in a call to allocation function ‘void* malloc(size_t)’ declared here
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
              ^~~~~~
cc1plus: all warnings being treated as errors
src/manifold/CMakeFiles/manifold.dir/build.make:92: recipe for target 'src/manifold/CMakeFiles/manifold.dir/src/boolean_result.cpp.o' failed
make[2]: *** [src/manifold/CMakeFiles/manifold.dir/src/boolean_result.cpp.o] Error 1
make[2]: Leaving directory '/app/manifold/build'
CMakeFiles/Makefile2:668: recipe for target 'src/manifold/CMakeFiles/manifold.dir/all' failed
make[1]: *** [src/manifold/CMakeFiles/manifold.dir/all] Error 2
make[1]: Leaving directory '/app/manifold/build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea what might cause this?

### LINKED ISSUE #467: build error
I followed the build instructions in the README, but got his error:
```
manifold/src/third_party/thrust/thrust/system/detail/sequential/trivial_copy.h:47:17: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing between 18446744022169944064 and 18446744073709551592 bytes into a region of size between 0 and 2147483647 [-Werror=stringop-overflow=]
   47 |     std::memmove(result, first, n * sizeof(T));
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by pca006132**
Closes #460
Closes #467

This is not a real fix, this is just to tell gcc that anything that reaches the malloc is at most `1 << 63`, and we have an exception otherwise.  I think the warning is most probably caused by Thrust (and interaction with something in gcc), as we don't really have a lot of large constants here. Previous experiment shows that making everything unsigned doesn't help, so it should not be related to having something negative and casting to unsigned. It is hard to get a MRE as the thrust code is just too complicated. This is the simplest way I can think of to please GCC.

@emil-peters @jw3126 can you please check if this works with your gcc version?

### CODE REVIEW

**Review by elalish — APPROVED** [review]
Thanks!

**Comment by pca006132** [comment]
I will merge this after confirming the build errors are fixed for them.

**Comment by jw3126** [comment]
Thanks a lot @pca006132  I can build using: 
```shell
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON .. && make
```
and `c++ (GCC) 13.1.1 20230429` and all tests pass:
```shell
[  PASSED  ] 158 tests.

  YOU HAVE 2 DISABLED TESTS
```

File: src/utilities/include/vec_dh.h [hunk 1]
```diff
@@ -253,6 +243,10 @@ class ManagedVec {
   static constexpr int DEVICE_MAX_BYTES = 1 << 16;
 
   static void mallocManaged(T **ptr, size_t bytes) {
+    // only exists to please the compiler
```
Comment (jw3126) [inline src/utilities/include/vec_dh.h:246]:
```suggestion
    // only exists to please the compiler
    // see https://github.com/elalish/manifold/pull/496 for background
```
