### PR TITLE
fixed properties

### LINKED ISSUE #1050: Properties regression
Well, score one for our release checklist - I found a bug that got by our tests:
image
It's not supposed to look noisy like that. Appears to be a problem in `GetMeshGL` - I'll get this fixed for v3.0.

### PR DESCRIPTION
**Pull request by elalish**
Fixes #1050 

I moved a bunch of debug functions around because I was having trouble printing my results.

### CODE REVIEW

File: src/properties.cpp [hunk 1]
```diff
@@ -89,7 +89,7 @@ struct UpdateProperties {
       auto old = std::atomic_exchange(
           reinterpret_cast<std::atomic<uint8_t>*>(&counters[propVert]),
           static_cast<uint8_t>(1));
-      if (old == 1) return;
+      if (old == 1) continue;
```
Comment (elalish) [inline src/properties.cpp:92]: This was the actual one-line fix for the bug.

File: test/test_main.cpp [hunk 2]
```diff
@@ -412,9 +412,10 @@ void CheckStrictly(const Manifold& manifold) {
   EXPECT_EQ(manifold.NumDegenerateTris(), 0);
 }
 
-void CheckGL(const Manifold& manifold) {
+void CheckGL(const Manifold& manifold, bool noMerge) {
   ASSERT_FALSE(manifold.IsEmpty());
   const MeshGL meshGL = manifold.GetMeshGL();
+  if (noMerge) EXPECT_EQ(manifold.NumVert(), meshGL.NumVert());
```
Comment (elalish) [inline test/test_main.cpp:418]: I added this test to catch the regression.
