### PR TITLE
Faster import

### LINKED ISSUE #1140: `NaN` values in vertex properties sometimes trigger `RuntimeError: memory access out of bounds`
Instancing manifold with the following `Mesh` triggers `memory access out of bounds` error for the WASM build. Reproducible at [manifoldcad.org](https://manifoldcad.org/).

```ts

const mesh = new Mesh({
	numProp: 8,
	vertProperties: new Float32Array([8.881783138210068e-16,-9.999999974752427e-7,15,-0.7071067690849304,8.659560603426554e-17,-0.7071067690849304,0,1.4142135381698608,-1,-9.999999974752427e-7,16,-0.7071067690849304,8.659560603426554e-17,-0.7071067690849304,0,0,2.4414916038513184,26.140724182128906,16,-0.6830127239227295,0.1830127090215683,-0.7071067690849304,26.105239868164062,0,3.4074172973632812,25.88190460205078,15,-0.6830127239227295,0.1830127090215683,-0.7071067690849304,26.105239868164062,1.4142135381698608,1,-9.999999974752427e-7,15,0,0,-1,0,2.4142136573791504,8.881783138210068e-16,-9.999999974752427e-7,15,0,0,-1,0,1.4142135381698608,3.4074172973632812,25.88190460205078,15,0,0,-1,26.105239868164062,1.4142135381698608,4.373342990875244,25.623085021972656,15,0,0,-1,26.105239868164062,2.4142136573791504,1,-9.999999974752427e-7,32,1,-1.2246468525851679e-16,0,0,19.414213180541992,1,-9.999999974752427e-7,15,1,-1.2246468525851679e-16,0,0,2.4142136573791504,4.373342990875244,25.623085021972656,15,0.9659258127212524,-0.258819043636322,0,26.105239868164062,2.4142136573791504,4.373342990875244,25.623085021972656,32,0.9659258127212524,-0.258819043636322,0,26.105239868164062,19.414213180541992,-1,-9.999999974752427e-7,32,0,0,1,0,21.414213180541992,1,-9.999999974752427e-7,32,0,0,1,0,19.414213180541992,4.373342990875244,25.623085021972656,32,0,0,1,26.105239868164062,19.414213180541992,2.4414916038513184,26.140724182128906,32,0,0,1,26.105239868164062,21.414213180541992,-1,-9.999999974752427e-7,16,-1,1.2246468525851679e-16,0,0,37.414215087890625,-1,-9.999999974752427e-7,32,-1,1.2246468525851679e-16,0,0,21.414213180541992,2.4414916038513184,26.140724182128906,32,-0.9659258127212524,0.258819043636322,0,26.105239868164062,21.414213180541992,2.4414916038513184,26.140724182128906,16,-0.9659258127212524,0.258819043636322,0,26.105239868164062,37.414215087890625,3.4074172973632812,25.88190460205078,15,-0.6830127239227295,0.1830127090215683,-0.7071067690849304,26.105239868164062,1.4142135381698608,2.4414916038513184,26.140724182128906,16,-0.6830127239227295,0.1830127090215683,-0.7071067690849304,26.105239868164062,0,12.531434059143066,50.5,16,-0.6123724579811096,0.3535533845424652,-0.7071067690849304,52.210479736328125,0,13.397459983825684,50,15,-0.6123724579811096,0.3535533845424652,-0.7071067690849304,52.210479736328125,1.4142135381698608,4.373342990875244,25.623085021972656,15,0,0,-1,26.105239868164062,2.4142136573791504,3.4074172973632812,25.88190460205078,15,0,0,-1,26.105239868164062,1.4142135381698608,13.397459983825684,50,15,0,0,-1,52.210479736328125,1.4142135381698608,14.263484954833984,49.5,15,0,0,-1,52.210479736328125,2.4142136573791504,4.373342990875244,25.623085021972656,32,0.9659258127212524,-0.258819043636322,0,26.105239868164062,19.414213180541992,4.373342990875244,25.623085021972656,15,0.9659258127212524,-0.258819043636322,0,26.105239868164062,2.4142136573791504,14.263484954833984,49.5,15,0.8660253882408142,-0.5,0,52.210479736328125,2.4142136573791504,14.263484954833984,49.5,32,0.8660253882408142,-0.5,0,52.210479736328125,19.414213180541992,2.4414916038513184,26.140724182128906,32,0,0,1,26.105239868164062,21.414213180541992,4.373342990875244,25.623085021972656,32,0,0,1,26.105239868164062,19.414213180541992,14.263484954833984,49.5,32,0,0,1,52.210479736328125,19.414213180541992,12.531434059143066,50.5,32,0,0,1,52.210479736328125,21.414213180541992,2.4414916038513184,26.140724182128906,16,-0.9659258127212524,0.258819043636322,0,26.105239868164062,37.414215087890625,2.4414916038513184,26.140724182128906,32,-0.9659258127212524,0.258819043636322,0,26.105239868164062,21.414213180541992,12.531434059143066,50.5,32,-0.8660253882408142,0.5,0,52.210479736328125,21.414213180541992,12.531434059143066,50.5,16,-0.8660253882408142,0.5,0,52.210479736328125,37.414215087890625,13.397459983825684,50,15,-0.6123724579811096,0.3535533845424652,-0.7071067690849304,52.210479736328125,1.4142135381698608,12.531434059143066,50.5,16,-0.6123724579811096,0.3535533845424652,-0.7071067690849304,52.210479736328125,0,28.58221435546875,71.41778564453125,16,-0.5,0.5,-0.7071067690849304,78.31571960449219,0,29.289321899414062,70.71067810058594,15,-0.5,0.5,-0.7071067690849304,78.31571960449219,1.4142135381698608,14.263484954833984,49.5,15,0,0,-1,52.210479736328125,2.4142136573791504,13.397459983825684,50,15,0,0,-1,52.210479736328125,1.4142135381698608,29.289321899414062,70.71067810058594,15,0,0,-1,78.31571960449219,1.4142135381698608,29.996429443359375,70.00357055664062,15,0,0,-1,78.31571960449219,2.4142136573791504,14.263484954833984,49.5,32,0.8660253882408142,-0.5,0,52.210479736328125,19.414213180541992,14.263484954833984,49.5,15,0.8660253882408142,-0.5,0,52.210479736328125,2.4142136573791504,29.996429443359375,70.00357055664062,15,0.7071067690849304,-0.7071067690849304,0,78.31571960449219,2.4142136573791504,29.996429443359375,70.00357055664062,32,0.7071067690849304,-0.7071067690849304,0,78.31571960449219,19.414213180541992,12.531434059143066,50.5,32,0,0,1,52.210479736328125,21.414213180541992,14.263484954833984,49.5,32,0,0,1,52.210479736328125,19.414213180541992,29.996429443359375,70.00357055664062,32,0,0,1,78.31571960449219,19.414213180541992,28.58221435546875,71.41778564453125,32,0,0,1,78.31571960449219,21.414213180541992,12.531434059143066,50.5,16,-0.8660253882408142,0.5,0,52.210479736328125,37.414215087890625,12.531434059143066,50.5,32,-0.8660253882408142,0.5,0,52.210479736328125,21.414213180541992,28.58221435546875,71.41778564453125,32,-0.7071067690849304,0.7071067690849304,0,78.31571960449219,21.414213180541992,28.58221435546875,71.41778564453125,16,-0.7071067690849304,0.7071067690849304,0,78.31571960449219,37.414215087890625,29.289321899414062,70.71067810058594,15,-0.5,0.5,-0.7071067690849304,78.31571960449219,1.4142135381698608,28.58221435546875,71.41778564453125,16,-0.5,0.5,-0.7071067690849304,78.31571960449219,0,49.5,87.46856689453125,16,-0.3535533845424652,0.6123724579811096,-0.7071067690849304,104.42095184326172,0,50,86.6025390625,15,-0.3535533845424652,0.6123724579811096,-0.7071067690849304,104.42095184326172,1.4142135381698608,29.996429443359375,70.00357055664062,15,0,0,-1,78.31571960449219,2.4142136573791504,29.289321899414062,70.71067810058594,15,0,0,-1,78.31571960449219,1.4142135381698608,50,86.6025390625,15,0,0,-1,104.42095184326172,1.4142135381698608,50.5,85.73651123046875,15,0,0,-1,104.42095184326172,2.4142136573791504,29.996429443359375,70.00357055664062,32,0.7071067690849304,-0.7071067690849304,0,78.31571960449219,19.414213180541992,29.996429443359375,70.00357055664062,15,0.7071067690849304,-0.7071067690849304,0,78.31571960449219,2.4142136573791504,50.5,85.73651123046875,15,0.5,-0.8660253882408142,0,104.42095184326172,2.4142136573791504,50.5,85.73651123046875,32,0.5,-0.8660253882408142,0,104.42095184326172,19.414213180541992,28.58221435546875,71.41778564453125,32,0,0,1,78.31571960449219,21.414213180541992,29.996429443359375,70.00357055664062,32,0,0,1,78.31571960449219,19.414213180541992,50.5,85.73651123046875,32,0,0,1,104.42095184326172,19.414213180541992,49.5,87.46856689453125,32,0,0,1,104.42095184326172,21.414213180541992,28.58221435546875,71.41778564453125,16,-0.7071067690849304,0.7071067690849304,0,78.31571960449219,37.414215087890625,28.58221435546875,71.41778564453125,32,-0.7071067690849304,0.7071067690849304,0,78.31571960449219,21.414213180541992,49.5,87.46856689453125,32,-0.5,0.8660253882408142,0,104.42095184326172,21.414213180541992,49.5,87.46856689453125,16,-0.5,0.8660253882408142,0,104.42095184326172,37.414215087890625,50,86.6025390625,15,-0.3535533845424652,0.6123724579811096,-0.7071067690849304,104.42095184326172,1.4142135381698608,49.5,87.46856689453125,16,-0.3535533845424652,0.6123724579811096,-0.7071067690849304,104.42095184326172,0,73.8592758178711,97.55850982666016,16,-0.1830127090215683,0.6830127239227295,-0.7071067690849304,130.5261993408203,0,74.11809539794922,96.59258270263672,15,-0.1830127090215683,0.6830127239227295,-0.7071067690849304,130.5261993408203,1.4142135381698608,50.5,85.73651123046875,15,0,0,-1,104.42095184326172,2.4142136573791504,50,86.6025390625,15,0,0,-1,104.42095184326172,1.4142135381698608,74.11809539794922,96.59258270263672,15,0,0,-1,130.5261993408203,1.4142135381698608,74.37691497802734,95.62665557861328,15,0,0,-1,130.5261993408203,2.4142136573791504,50.5,85.73651123046875,32,0.5,-0.8660253882408142,0,104.42095184326172,19.414213180541992,50.5,85.73651123046875,15,0.5,-0.8660253882408142,0,104.42095184326172,2.4142136573791504,74.37691497802734,95.62665557861328,15,0.258819043636322,-0.9659258127212524,0,130.5261993408203,2.4142136573791504,74.37691497802734,95.62665557861328,32,0.258819043636322,-0.9659258127212524,0,130.5261993408203,19.414213180541992,49.5,87.46856689453125,32,0,0,1,104.42095184326172,21.414213180541992,50.5,85.73651123046875,32,0,0,1,104.42095184326172,19.414213180541992,74.37691497802734,95.62665557861328,32,0,0,1,130.5261993408203,19.414213180541992,73.8592758178711,97.55850982666016,32,0,0,1,130.5261993408203,21.414213180541992,49.5,87.46856689453125,16,-0.5,0.8660253882408142,0,104.42095184326172,37.414215087890625,49.5,87.46856689453125,32,-0.5,0.8660253882408142,0,104.42095184326172,21.414213180541992,73.8592758178711,97.55850982666016,32,-0.258819043636322,0.9659258127212524,0,130.5261993408203,21.414213180541992,73.8592758178711,97.55850982666016,16,-0.258819043636322,0.9659258127212524,0,130.5261993408203,37.414215087890625,74.11809539794922,96.59258270263672,15,-0.1830127090215683,0.6830127239227295,-0.7071067690849304,130.5261993408203,1.4142135381698608,73.8592758178711,97.55850982666016,16,-0.1830127090215683,0.6830127239227295,-0.7071067690849304,130.5261993408203,0,NaN,NaN,NaN,0,0.7071067690849304,-0.7071067690849304,156.63143920898438,0,NaN,NaN,NaN,0,0.7071067690849304,-0.7071067690849304,156.63143920898438,1.4142135381698608,74.37691497802734,95.62665557861328,15,0,0,-1,130.5261993408203,2.4142136573791504,74.11809539794922,96.59258270263672,15,0,0,-1,130.5261993408203,1.4142135381698608,NaN,NaN,NaN,0,0,-1,156.63143920898438,1.4142135381698608,NaN,NaN,NaN,0,0,-1,156.63143920898438,2.4142136573791504,74.37691497802734,95.62665557861328,32,0.258819043636322,-0.9659258127212524,0,130.5261993408203,19.414213180541992,74.37691497802734,95.62665557861328,15,0.258819043636322,-0.9659258127212524,0,130.5261993408203,2.4142136573791504,NaN,NaN,NaN,0,-1,0,156.63143920898438,2.4142136573791504,NaN,NaN,NaN,0,-1,0,156.63143920898438,19.414213180541992,73.8592758178711,97.55850982666016,32,0,0,1,130.5261993408203,21.414213180541992,74.37691497802734,95.62665557861328,32,0,0,1,130.5261993408203,19.414213180541992,NaN,NaN,NaN,0,0,1,156.63143920898438,19.414213180541992,NaN,NaN,NaN,0,0,1,156.63143920898438,21.414213180541992,73.8592758178711,97.55850982666016,16,-0.258819043636322,0.9659258127212524,0,130.5261993408203,37.414215087890625,73.8592758178711,97.55850982666016,32,-0.258819043636322,0.9659258127212524,0,130.5261993408203,21.414213180541992,NaN,NaN,NaN,0,1,0,156.63143920898438,21.414213180541992,NaN,NaN,NaN,0,1,0,156.63143920898438,37.414215087890625,NaN,NaN,NaN,2.009718280956632e-16,-0.7071067690849304,-0.7071067690849304,156.63143920898438,1.4142135381698608,NaN,NaN,NaN,2.009718280956632e-16,-0.7071067690849304,-0.7071067690849304,156.63143920898438,0,-9.999999974752427e-7,99,16,2.009718280956632e-16,-0.7071067690849304,-0.7071067690849304,256.6314392089844,0,-9.999999974752427e-7,100,15,2.009718280956632e-16,-0.7071067690849304,-0.7071067690849304,256.6314392089844,1.4142135381698608,NaN,NaN,NaN,0,0,-1,156.63143920898438,2.4142136573791504,NaN,NaN,NaN,0,0,-1,156.63143920898438,1.4142135381698608,-9.999999974752427e-7,100,15,0,0,-1,256.6314392089844,1.4142135381698608,-9.999999974752427e-7,101,15,0,0,-1,256.6314392089844,2.4142136573791504,NaN,NaN,NaN,-2.8421708795129297e-16,1,0,156.63143920898438,19.414213180541992,NaN,NaN,NaN,-2.8421708795129297e-16,1,0,156.63143920898438,2.4142136573791504,-9.999999974752427e-7,101,15,-2.8421708795129297e-16,1,0,256.6314392089844,2.4142136573791504,-9.999999974752427e-7,101,32,-2.8421708795129297e-16,1,0,256.6314392089844,19.414213180541992,NaN,NaN,NaN,0,0,1,156.63143920898438,21.414213180541992,NaN,NaN,NaN,0,0,1,156.63143920898438,19.414213180541992,-9.999999974752427e-7,101,32,0,0,1,256.6314392089844,19.414213180541992,-9.999999974752427e-7,99,32,0,0,1,256.6314392089844,21.414213180541992,NaN,NaN,NaN,2.8421708795129297e-16,-1,0,156.63143920898438,37.414215087890625,NaN,NaN,NaN,2.8421708795129297e-16,-1,0,156.63143920898438,21.414213180541992,-9.999999974752427e-7,99,32,2.8421708795129297e-16,-1,0,256.6314392089844,21.414213180541992,-9.999999974752427e-7,99,16,2.8421708795129297e-16,-1,0,256.6314392089844,37.414215087890625,-1,-9.999999974752427e-7,16,-1.2246468525851679e-16,-1,0,-1,1.4210854715202004e-14,8.881783138210068e-16,-9.999999974752427e-7,15,-1.2246468525851679e-16,-1,0,8.881784197001252e-16,-1,1,-9.999999974752427e-7,15,-1.2246468525851679e-16,-1,0,1,-1,1,-9.999999974752427e-7,32,-1.2246468525851679e-16,-1,0,1,16,-1,-9.999999974752427e-7,32,-1.2246468525851679e-16,-1,0,-1,16,-9.999999974752427e-7,99,32,-1,-2.8421708795129297e-16,0,1,16,-9.999999974752427e-7,101,32,-1,-2.8421708795129297e-16,0,-1,16,-9.999999974752427e-7,101,15,-1,-2.8421708795129297e-16,0,-1,-1,-9.999999974752427e-7,100,15,-1,-2.8421708795129297e-16,0,-8.881784197001252e-16,-1,-9.999999974752427e-7,99,16,-1,-2.8421708795129297e-16,0,1,1.4210854715202004e-14]),
	triVerts: new Uint32Array([0,1,3,1,2,3,4,5,7,5,6,7,8,9,11,9,10,11,12,13,15,13,14,15,16,17,19,17,18,19,20,21,23,21,22,23,24,25,27,25,26,27,28,29,31,29,30,31,32,33,35,33,34,35,36,37,39,37,38,39,40,41,43,41,42,43,44,45,47,45,46,47,48,49,51,49,50,51,52,53,55,53,54,55,56,57,59,57,58,59,60,61,63,61,62,63,64,65,67,65,66,67,68,69,71,69,70,71,72,73,75,73,74,75,76,77,79,77,78,79,80,81,83,81,82,83,84,85,87,85,86,87,88,89,91,89,90,91,92,93,95,93,94,95,96,97,99,97,98,99,100,101,103,101,102,103,104,105,107,105,106,107,108,109,111,109,110,111,112,113,115,113,114,115,116,117,119,117,118,119,120,121,123,121,122,123,124,125,127,125,126,127,128,129,131,129,130,131,132,133,135,133,134,135,136,137,139,137,138,139,140,141,144,141,143,144,141,142,143,145,146,149,146,148,149,146,147,148]),
	mergeFromVert: new Uint32Array([5,6,9,10,13,14,16,17,18,19,20,21,24,25,26,28,29,30,32,33,34,36,37,38,39,40,41,44,45,46,48,49,50,52,53,54,56,57,58,59,60,61,64,65,66,68,69,70,72,73,74,76,77,78,79,80,81,84,85,86,88,89,90,92,93,94,96,97,98,99,100,101,104,105,106,108,109,110,112,113,114,116,117,118,119,120,121,124,125,126,128,129,130,132,133,134,136,137,138,139,140,141,142,143,144,145,146,147,148,149]),
	mergeToVert: new Uint32Array([0,3,4,7,8,11,1,12,15,2,3,2,7,3,23,11,7,27,15,11,31,2,15,35,22,23,22,27,23,43,31,27,47,35,31,51,22,35,55,42,43,42,47,43,63,51,47,67,55,51,71,42,55,75,62,63,62,67,63,83,71,67,87,75,71,91,62,75,95,82,83,82,87,83,103,91,87,107,95,91,111,82,95,115,102,103,102,107,103,123,111,107,127,115,111,131,102,115,135,122,1,0,4,8,12,135,131,127,123,122]),
});
	
const result = new Manifold(mesh);
```

The vertex properties have quite a lot of `NaN` values due to problems on my side. The issue is that I think Manifold *should not crash* and possibly inform the user about the bad input. But I might be wrong. Feel free to turn this into a discussion if it seems irrelevant to you.

The interesting part is that Manifold does not always crashes when there are `NaN` values in the vertex properties. For example, if I pass only the vertex positions (with `NaN` values), it does not crash.

### PR DESCRIPTION
**Pull request by pca006132**
Optimize #1138 a bit.

1. Avoids calling fill after resize when possible. We often use resize and then fill in the vectors with various values, so we don't have to ensure that the vector content is not uninitialized values after calling resize. This adds a `resize_nofill` to explicitly avoid initializing the buffer.
2. Speed up simplification by trying to do things in parallel.
3. Fixing `FlagEdge` as mentioned in #970

This seems to be faster for cases where there are not too many edges to simplify. However, for Samples.Sponge4, this is slower, probably because there are too many edges to simplify. Will try to fix that.

Should also fix #1140.

### CODE REVIEW

**Comment by pca006132** [comment]
Basically, around 10% improvement for `perfTest` and mesh import.

**Comment by pca006132** [comment]
Need to think about why the sequential version is not working...

**Comment by pca006132** [comment]
Some `resize_nofill` is probably wrong... need to check them sometime later.

File: src/edge_op.cpp [hunk 1]
```diff
@@ -109,14 +117,75 @@ struct SwappableEdge {
   }
 };
 
-struct SortEntry {
-  int start;
-  int end;
-  size_t index;
-  inline bool operator<(const SortEntry& other) const {
-    return start == other.start ? end < other.end : start < other.start;
+struct FlagStore {
```
Comment (elalish) [inline src/edge_op.cpp:120]: Perhaps a comment about what this struct is used for? I don't entirely follow from reading it.

File: src/edge_op.cpp [hunk 2]
```diff
@@ -132,30 +201,62 @@ void Manifold::Impl::CleanupTopology() {
...
+    if (nbEdges > 1e5) {
+      entries.resize_nofill(nbEdges);
+      sequence(entries.begin(), entries.end());
+      stable_sort(entries.begin(), entries.end(), [&](int a, int b) {
+        const auto& self = halfedge_[a];
+        const auto& other = halfedge_[b];
+        // place all backward edges at the end
+        if (!other.IsForward()) return true;
+        if (!self.IsForward()) return false;
+        // dictionary order based on start and end vertices
```
Comment (elalish) [inline src/edge_op.cpp:222]: Why do we sort differently for parallel and serial?

File: src/impl.cpp [hunk 3]
```diff
@@ -470,11 +470,11 @@ void Manifold::Impl::Update() {
...
-  vertPos_.resize(0);
-  halfedge_.resize(0);
-  vertNormal_.resize(0);
-  faceNormal_.resize(0);
-  halfedgeTangent_.resize(0);
+  vertPos_.clear();
+  halfedge_.clear();
+  vertNormal_.clear();
+  faceNormal_.clear();
+  halfedgeTangent_.clear();
```
Comment (elalish) [inline src/impl.cpp:477]: 👍

**Review by elalish — COMMENTED** [review]
Weird that knot42 is non-finite; hopefully that's easy to track down. Did you see the error about magic-nix? Looks like that's already past its drop-dead date.

File: src/edge_op.cpp (hunk 2 above)
Comment (pca006132) [reply src/edge_op.cpp:229]: This is now explained in the comment:

```
      // Note that this is slightly different from the single thread version
      // because we store all indices instead of just indices of forward
      // halfedges. Backward halfedges are placed at the end by modifying the
      // comparison function.
```

File: src/csg_tree.cpp [hunk 4]
```diff
@@ -206,15 +206,15 @@ std::shared_ptr<CsgLeafNode> CsgLeafNode::Compose(
...
+  combined.vertPos_.resize_nofill(numVert);
+  combined.halfedge_.resize_nofill(2 * numEdge);
+  combined.faceNormal_.resize_nofill(numTri);
+  combined.halfedgeTangent_.resize_nofill(2 * numEdge);
+  combined.meshRelation_.triRef.resize_nofill(numTri);
   if (numPropOut > 0) {
     combined.meshRelation_.numProp = numPropOut;
     combined.meshRelation_.properties.resize(numPropOut * numPropVert, 0);
-    combined.meshRelation_.triProperties.resize(numTri);
+    combined.meshRelation_.triProperties.resize(numTri, ivec3(0));
```
Comment (pca006132) [inline src/csg_tree.cpp:217]: This was causing the test failure. I forgot what `triProperties` is used for and why are we adding it instead of copying them in with a per input mesh offset.

Also, the weird thing is that the bug is order dependent. I am rerunning the tests with shuffling enabled to try and see if there is something else that is similar.

Comment (pca006132) [reply src/csg_tree.cpp]: Ah, I was mistaken, this is not the issue. Halfedge tangent is the issue. I guess this may be caused by having empty halfedge tangents?

File: src/impl.h [hunk 5]
```diff
@@ -96,6 +96,27 @@ struct Manifold::Impl {
       return;
     }
 
+    if (!manifold::all_of(meshGL.vertProperties.begin(),
+                          meshGL.vertProperties.end(),
+                          [](Precision x) { return std::isfinite(x); })) {
+      MarkFailure(Error::NonFiniteVertex);
```
Comment (elalish) [inline src/impl.h:102]: 👍

**Review by elalish — APPROVED** [review]
Thanks, LGTM.
