### PR TITLE
csg-tree: fix subtraction

### LINKED ISSUE #1102: CSG tree simplify subtractions
It turns out I forgot to simplify consecutive subtractions: `(a - b) - c` into `a - (b + c)`. Should be simple by duplicating destination into positive and negative destination... Will fix this weekend.

### PR DESCRIPTION
**Pull request by pca006132**
Closes #1102.

### CODE REVIEW

File: src/csg_tree.cpp [hunk 1]
```diff
@@ -494,7 +498,7 @@ std::shared_ptr<CsgLeafNode> CsgOpNode::ToLeafNode() const {
   // Before performing boolean operations, we should make sure that all children
   // are `CsgLeafNodes`, i.e. are actual meshes that can be operated on. Hence,
   // we do it in two steps:
-  // 1. Populate `children` (`left_children` and `right_children`, see below)
+  // 1. Populate `children` (`positive_children` and `positive_children`)
```
Comment (elalish) [inline src/csg_tree.cpp:501]: and negative?

**Review by elalish — APPROVED** [review]
Thanks!

File: src/csg_tree.cpp (hunk 1 above)
Comment (pca006132) [reply src/csg_tree.cpp:501]: nice catch
