### PR TITLE
Misc. changes

### LINKED ISSUE #744: better error handling
e.g. poison the object that thrown an error, so we will not observe things in inconsistent states after throwing exceptions. This can happen when we have shared csg nodes, and got an error when evaluated for the first time, and inconsistent when trying to evaluate for the second time.

### PR DESCRIPTION
**Pull request by pca006132**
Fixes #744.

1. Propagate errors in mesh boolean, transform and compose. Probably there are still some other operations that we should propagate the error.
2. Use 64-bit integers for MeshGL64. Note that this is not yet tested, I just checked it can compile. (ideally nothing else can go wrong considering we don't do raw pointer operations...). We should check if the APIs make sense.

I don't plan to do 64-bit run ID or mesh ID, as I don't think users will ever want that...? It might make sense in some scientific computation situation to handle large meshes, but it doesn't make sense to do boolean on several hundred million meshes, I guess...

Checklist for error propagation, feel free to add to this list, so I can add them in this PR:
1. Warp

### CODE REVIEW

File: src/manifold/include/manifold/manifold.h [hunk 1]
```diff
@@ -37,22 +37,12 @@ class CsgLeafNode;
  *  @{
  */
 
-template <typename Precision>
+template <typename Precision, typename I = uint32_t>
```
Comment (elalish) [inline src/manifold/include/manifold/manifold.h:40]: Honestly, does it hurt anything for runIndex and runOriginalID to be 64 bit? They're very short vectors anyway. Seems simpler and more fitting with the name `MeshGL64` for everything to be 64 bit instead of just some.

File: src/manifold/src/csg_tree.cpp [hunk 2]
```diff
@@ -478,9 +483,9 @@ std::shared_ptr<Manifold::Impl> CsgOpNode::BatchBoolean(
           continue;
         }
         group.run([&, a, b]() {
-          const Manifold::Impl *aImpl;
-          const Manifold::Impl *bImpl;
```
Comment (elalish) [inline src/manifold/src/csg_tree.cpp:482]: Were these lines even doing anything before? Can we just delete them now too?

File: src/manifold/src/impl.h [hunk 3]
```diff
@@ -183,8 +183,9 @@ struct Manifold::Impl {
         }
         if (numProp > 0) {
           meshRelation_.triProperties.push_back(
-              ivec3(meshGL.triVerts[3 * i], meshGL.triVerts[3 * i + 1],
-                    meshGL.triVerts[3 * i + 2]));
+              ivec3((uint32_t)meshGL.triVerts[3 * i],
+                    (uint32_t)meshGL.triVerts[3 * i + 1],
+                    (uint32_t)meshGL.triVerts[3 * i + 2]));
```
Comment (elalish) [inline src/manifold/src/impl.h:188]: which casting syntax do you prefer?

**Review by elalish — APPROVED** [review]
As far as a checklist, I guess it's everything non-static in `manifold.h` that returns a `Manifold`?

File: src/manifold/src/csg_tree.cpp (hunk 2 above)
Comment (pca006132) [reply src/manifold/src/csg_tree.cpp:482]: sure

File: src/manifold/src/impl.h (hunk 3 above)
Comment (pca006132) [reply src/manifold/src/impl.h:188]: ah, actually `static_cast<uint32_t>`, will change.

File: src/manifold/include/manifold/manifold.h (hunk 1 above)
Comment (pca006132) [reply src/manifold/include/manifold/manifold.h:40]: Sure

**Comment by pca006132** [comment]
Thinking about it, some functions in `Manifold` should also return 64-bit integer for this.

**Comment by pca006132** [comment]
Notably, `OriginalID` is now returning `std::optional<size_t>`, and is empty when the mesh is not an original.

**Comment by pca006132** [comment]
I was looking into other functions that do unary operations on a manifold. Apparently, they copy the `Impl` data structure, so I think they should have the error code copied with them together. I forgot who can we have those error conditions and whether our internal data structures are still safe to operate on when an error occurs though, so not sure if I should add guard in those operations to early return.

**Comment by pca006132** [comment]
maybe I will fix the wasm issue tmr

**Comment by elalish** [comment]
IIRC, the manifold is set to empty when any of the error conditions occur - at least that was the intention. So I believe that yes, they should all be in a safe state.

File: src/manifold/include/manifold/manifold.h [hunk 4]
```diff
@@ -222,14 +223,14 @@ class Manifold {
...
-  int NumPropVert() const;
+  size_t NumVert() const;
+  size_t NumEdge() const;
+  size_t NumTri() const;
+  size_t NumProp() const;
+  size_t NumPropVert() const;
   Box BoundingBox() const;
   double Precision() const;
-  int Genus() const;
+  size_t Genus() const;
```
Comment (elalish) [inline src/manifold/include/manifold/manifold.h:233]: Genus is signed - you get negative values for multiple disconnected objects.

File: src/utilities/include/manifold/iters.h [hunk 5]
```diff
@@ -190,8 +190,7 @@ struct CountingIterator {
   }
 };
 
-template <typename T>
-CountingIterator<T> countAt(T i) {
+constexpr CountingIterator<size_t> countAt(size_t i) {
```
Comment (elalish) [inline src/utilities/include/manifold/iters.h:193]: 👍

File: test/test_main.cpp [hunk 6]
```diff
@@ -203,7 +203,7 @@ MeshGL WithIndexColors(const MeshGL& in) {
   out.runIndex.clear();
   out.runTransform.clear();
   out.faceID.clear();
-  out.runOriginalID = {Manifold::ReserveIDs(1)};
+  out.runOriginalID = {static_cast<uint32_t>(Manifold::ReserveIDs(1))};
```
Comment (elalish) [inline test/test_main.cpp:206]: Hmm, I think I see now why you recommended keeping the IDs as uint32_t across the board. The casting is annoying - and *we* know the values are sequential and so down-casting is safe, but that's not a common expectation (people might think this is a GUID, and maybe it could be someday). Sorry for the flip-flop, but I think I like it better the first way now.

**Review by elalish — CHANGES_REQUESTED** [review]

**Review by elalish — APPROVED** [review]
Thanks!
