### PR TITLE
Fix properties

### LINKED ISSUE #579: Wrong vertex normals and uvs after boolean subtraction
I have two manifolds `a` and `b`. Both have 8 vertex properties - 3 for coordinates, 3 for normals, 2 for uvs).

Manifold `a` is a result of previous boolean operations and you can see it in the following picture. One of its surfaces has a UV debug texture assigned. The short blue segments pointing out from the textured surface shows vertex normals for all the vertices that are involved in any triangle belonging to this surface. 

image

Manifold `b` is a simple cuboid larger then manifold `a` and translated down a little bit. Here is a picture of both manifold `a` and `b` in one scene.

image

When `b` is subtracted from `a` (manifold `a_minus_b`), something bad happens with the normals and uvs on the textured surface. See the picture below.

image

The problematic surface is composed of three triangles. The problem is that two of the triangles uses a vertex which has normal and uv that would be good for the left adjacent surface, but not for this.

The problem occurs in specific situations only. For example, if I move the manifold `b` down by a different offset, the problem disappears. It seems to me that offsets which don't have accurate numeric representation (like multiples of 1/3) triggers this more often.

In case you would have time to look into this, I attach a MeshGL dump of all the manifolds - `a`, `b` and `a_minus_b`. The problematic triangles are 40 and 46. They use vertex 50 which has inappropriate normal and uv. I would expect that these triangles will use vertex 68 instead as it is used in the only correct triangle 38 for this surface.

[wrong_normals_and_uvs_mesh_dump.txt](https://github.com/elalish/manifold/files/13167961/wrong_normals_and_uvs_mesh_dump.txt)

### PR DESCRIPTION
**Pull request by elalish**
Follow-up on #581
Fixes #579 

Third time's the charm! Of course I had to write a hideous amount of code and get nowhere to finally realize the simple solution. This even allowed me to simplify our code a bit, since I removed a previous convoluted bit I had put in trying to fix related issues.

### CODE REVIEW

File: src/manifold/src/boolean_result.cpp [hunk 1]
```diff
@@ -567,7 +567,7 @@ void CreateProperties(Manifold::Impl &outR, const Vec<TriRef> &refPQ,
           }
           if (uvw[j] == 0) edge = j;
         }
-        if (edge >= 0) {
+        if (edge >= 0) {  // This misses some edges
```
Comment (elalish) [inline src/manifold/src/boolean_result.cpp:570]: This is the root cause of the problem: when an edge is collapsed (before this step) you can end up with verts that refer (through refPQ) to a triangle that they are now outside of, since they were merged with their neighboring triangle but the references were not updated. This would be fine, except here I'm assuming I can tell when a vert is on a retained edge by checking its barycentric coordinates - but I miss these ones. So I end up assigning a key with only the `meshID` and `vert`, which isn't enough when the other side of the retained edge might have different properties.

File: src/manifold/src/boolean_result.cpp [hunk 2]
```diff
@@ -772,6 +772,7 @@ Manifold::Impl Boolean3::Result(OpType op) const {
 
   Vec<TriRef> refPQ = UpdateReference(outR, inP_, inQ_, invertQ);
 
+  // This causes some verts to be outside of their refPQ triangle.
   outR.SimplifyTopology();
```
Comment (elalish) [inline src/manifold/src/boolean_result.cpp:776]: I tried just reversing the order - create the properties first, and then simplify the topology. However, in this case it's very difficult to keep from duplicating prop verts (CoplanarProp test does a good job catching this). This might not seem like a huge deal, but they tend to continue to multiply, until your final output going to the renderer is basically triangle soup, even if the geometry is manifold.

File: test/test_main.cpp [hunk 3]
```diff
@@ -396,7 +396,7 @@ void RelatedGL(const Manifold& out, const std::vector<MeshGL>& originals,
             const float volumeP =
                 glm::dot(edgesP[0], glm::cross(edgesP[1], edgesP[2]));
 
-            ASSERT_LE(volumeP, area * 100 * out.Precision());
+            ASSERT_LE(volumeP, area * out.Precision());
```
Comment (elalish) [inline test/test_main.cpp:399]: Our regular tests would have caught this bug if I hadn't put in this *100, which has the look of me just getting frustrated at some point.

Comment (pca006132) [reply test/test_main.cpp:399]: interesting, I think we should probably go over all tests to see if there are suspicious ones

File: src/manifold/src/boolean_result.cpp [hunk 4]
```diff
@@ -541,23 +540,22 @@ void CreateProperties(Manifold::Impl &outR, const Vec<TriRef> &refPQ,
...
+                                : PQ ? inP.meshRelation_.triProperties[ref.tri]
+                                     : inQ.meshRelation_.triProperties[ref.tri];
 
     for (const int i : {0, 1, 2}) {
       const int vert = outR.halfedge_[3 * tri + i].startVert;
       const glm::vec3 &uvw = bary[3 * tri + i];
 
       glm::ivec4 key(PQ, idMissProp, -1, -1);
       if (oldNumProp > 0) {
-        key[1] = vert;
```
Comment (elalish) [inline src/manifold/src/boolean_result.cpp:559]: This was the key fix: for anything close to a retained vert, only key on the propVert, since the separate verts are close together and will get collapsed anyway - this was causing us to duplicate propVerts unnecessarily.

File: src/manifold/src/boolean_result.cpp [hunk 5]
```diff
@@ -770,11 +771,11 @@ Manifold::Impl Boolean3::Result(OpType op) const {
...
     ASSERT(outR.IsManifold(), logicErr, "triangulated mesh is not manifold!");
 
-  Vec<TriRef> refPQ = UpdateReference(outR, inP_, inQ_, invertQ);
+  CreateProperties(outR, inP_, inQ_);
 
-  outR.SimplifyTopology();
+  UpdateReference(outR, inP_, inQ_, invertQ);
 
-  CreateProperties(outR, refPQ, inP_, inQ_);
+  outR.SimplifyTopology();
```
Comment (elalish) [inline src/manifold/src/boolean_result.cpp:778]: No need for `refPQ` anymore since now everything happens in a logical order.
