### PR TITLE
make boolean deterministic

### LINKED ISSUE #1177: Determinism / Repeatability?
This is a mostly question more than an issue.

Does  Manifold make any guarantees about the repeatability of the results?  That is, if you run it again or run it on a different machine, will you get the same results (where "same" includes the order of the vertices and output faces, as well as the actual geometry of the output)?

I am guessing the answer is "no", but would be happily surprised to learn otherwise.  If the answer is "no", a second question would be: if there is no parallelism used to get the answer (either because it is turned off, or because the problem size is quite small), might we expect such determinism? I suspect this mostly comes down to: are any sorts used stable sorts, and do you avoid hashing on pointers?  If the answer is still "no" for small problems / parallelism turned off, then how hard would it be to make it deterministic/repeatable/portable in those cases?

The reason I care is two-fold.

(1) It makes regression testing much easier, and Blender's regression tests typically rely on such a guarantee. If Manifold is repeatable on small cases, that would be sufficient for this.

(2) There are cases where non-repeatability can affect the visual appearance of a render or animation.  E.g., if you get different results frame-to-frame in an animation, the animation can flicker. Or, if the user has relied on element indices in making procedural postprocessing of the Boolean result (using our procedural system "Geometry Nodes") then they will not get repeatable results. They are not supposed to do this latter thing, so this is less important; but nevertheless, some users do.

### PR DESCRIPTION
**Pull request by pca006132**
Closes #1177

### CODE REVIEW

File: src/boolean_result.cpp [hunk 1]
```diff
@@ -658,6 +658,39 @@ void CreateProperties(Manifold::Impl &outR, const Manifold::Impl &inP,
     }
   }
 }
+
+void ReorderHalfedges(VecView<Halfedge> &halfedges) {
+  // halfedges in the same face are added in non-deterministic order, so we have
+  // to reorder them for determinism
```
Comment (elalish) [inline src/boolean_result.cpp:664]: There's a `CreateHalfedges` call at the end of `Face2Tri` - would it be more efficient to merge this logic in there?

File: src/edge_op.cpp [hunk 2]
```diff
@@ -160,32 +160,21 @@ struct FlagStore {
...
+    for (const auto& tmp : stores) {
+      sizes.push_back(total_size);
+      total_size += tmp.size();
     }
+    result.resize(total_size);
+    for_each_n(ExecutionPolicy::Seq, countAt(0), stores.size(), [&](size_t i) {
+      std::copy(stores[i].begin(), stores[i].end(), result.begin() + sizes[i]);
+    });
+    stable_sort(autoPolicy(result.size()), result.begin(), result.end());
+    for (size_t x : result) f(x);
```
Comment (elalish) [inline src/edge_op.cpp:177]: Simpler *and* more deterministic - I love it!

**Review by elalish — COMMENTED** [review]
How much of #1177 does this solve?

**Comment by pca006132** [comment]
Only nondeterminism in csg tree is left, I think. And it shouldn't be too hard to fix, but will need some benchmark on that.

File: src/edge_op.cpp (hunk 2 above)
Comment (pca006132) [reply src/edge_op.cpp:177]: It was supposed to be deterministic, I just somehow messed it up :P

File: src/boolean_result.cpp (hunk 1 above)
Comment (pca006132) [reply src/boolean_result.cpp:664]: Probably, but `CreateHalfedges` is called in multiple places and this reordering is only concerned with boolean result. I think we can try to optimize this later when this is causing slowness.

**Review by elalish — APPROVED** [review]

**Comment by pca006132** [comment]
I think I can adapt @howardt's simple check for determinism and throw it into places like Sponge4 and the ember test. If they all pass, we can be quite confident that we are deterministic. Will do that maybe tmr.

**Comment by pca006132** [comment]
Tested this on top of #1186, and the slowdown is around 1% up to 4% with benchmarks in ember test. I expect future patches to convert stable sort to radix sort for example to easily get that back.

**Comment by pca006132** [comment]
Found one missing case: In `DedupeEdge` is quite complicated, we need to ensure the same set of edges are marked duplicates. It is fixed now, and so far the 999 ember test cases are deterministic, at least with two executions.

**Comment by pca006132** [comment]
OK this took a while, but I can no longer find anything non-deterministic now. SDF is out of scope though.

**Comment by pca006132** [comment]
I think if we remove the usage of fma and acos (with approximation), our boolean is probably deterministic across machines as well. But that can be a bit harder to prove...

File: test/samples_test.cpp [hunk 3]
```diff
@@ -291,6 +291,9 @@ TEST(Samples, Sponge4) {
     ExportMesh("mengerSponge.glb", out, options);
   }
 #endif
+  Manifold sponge2 = MengerSponge(4);
+  std::pair<Manifold, Manifold> cutSponge2 = sponge2.SplitByPlane({1, 1, 1}, 0);
+  CheckGLEquiv(cutSponge.first.GetMeshGL(), cutSponge2.first.GetMeshGL());
```
Comment (elalish) [inline test/samples_test.cpp:296]: 👍

File: src/csg_tree.cpp [hunk 4]
```diff
@@ -353,50 +351,44 @@ std::shared_ptr<CsgLeafNode> BatchBoolean(
...
-    results.pop_back();
-    std::pop_heap(results.begin(), results.end(), cmpFn);
-    auto b = std::move(results.back());
-    results.pop_back();
-    // boolean operation
-    auto result = SimpleBoolean(*a->GetImpl(), *b->GetImpl(), operation);
-    if (results.size() == 0) return result;
-    results.push_back(result);
-    std::push_heap(results.begin(), results.end(), cmpFn);
+    for (size_t i = 0; i < 4 && results.size() > 1; i++) {
```
Comment (elalish) [inline src/csg_tree.cpp:365]: Did this fix the CSG tree non-determinism too?

Comment (pca006132) [reply src/csg_tree.cpp:365]: Yes, batch boolean is now deterministic.

**Comment by elalish** [comment]
Go ahead and merge it when you feel ready. This is great!

**Comment by pca006132** [comment]
I will wait for #1186, considering it is close to merging, it is easier to fix conflicts.
